
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia-container
          image: josh1991/kubia-v1:latest
          ports:
            - containerPort: 8080
